from datetime import date, datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from models.enums import IngestionStatus, SourceType


class DocumentCreate(BaseModel):
    """Fields a client may send when registering a document."""

    # Not included in the request:
    #   id, created_at              -> generated by the database
    #   user_id                     -> taken from the authenticated user in the route
    #   status, error, ingested_at  -> obtained from the ingestion pipeline

    title: str = Field(min_length=1, description="Title of the document")
    source_type: SourceType = Field(description="What kind of material this is")
    file_path: str = Field(description="Relative path to the stored file")
    content_hash: str = Field(
        description="Hash of the file contents; prevents re-ingesting duplicates"
    )
    origin: str | None = Field(
        None, description="Where it came from, e.g. a URL or the original path"
    )
    author: str | None = Field(
        None, description="Author of the source material, if known"
    )
    created_date: date | None = Field(
        None, description="Date of the source itself, not of the upload"
    )


class DocumentUpdate(BaseModel):
    """Fields a client may change. All optional; PATCH sends only what changes."""

    title: str = Field(None, min_length=1, description="Title of the document")
    origin: str | None = Field(
        None, description="Where it came from, e.g. a URL or the original path"
    )
    source_type: SourceType = Field(None, description="What kind of material this is")
    author: str | None = Field(
        None, description="Author of the source material, if known"
    )
    created_date: date | None = Field(
        None, description="Date of the source itself, not of the upload"
    )


class DocumentRead(BaseModel):
    """What the API returns, including the server-owned fields."""

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: UUID = Field(description="Unique identifier for the document")
    title: str = Field(description="Title of the document")
    source_type: SourceType = Field(description="What kind of material this is")
    origin: str | None = Field(
        None, description="Where it came from, e.g. a URL or the original path"
    )
    author: str | None = Field(
        None, description="Author of the source material, if known"
    )
    created_date: date | None = Field(
        None, description="Date of the source itself, not of the upload"
    )
    file_path: str = Field(description="Relative path to the stored file")
    content_hash: str = Field(
        description="Hash of the file contents; prevents re-ingesting duplicates"
    )
    status: IngestionStatus = Field(description="Status of the document")
    ingested_at: datetime | None = Field(
        None, description="When the ingestion pipeline finished, if it has"
    )
    created_at: datetime = Field(description="When the entry was created")
